## Config server port
server:
   port: 9999

## Spring database schema
spring:
   jpa:
      show-sql: true
      properties:
         hibernate:
            default_schema: adhyapan

---
## Spring Datasource (DatasourceAutoConfiguration & DataSourceProperties)
spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/mocktestdb
      username: postgres
      password: root

---

## Security with oauth2
spring:         
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: http://localhost:8083/auth/realms/adhyapan
               jwk-set-uri: http://localhost:8083/auth/realms/adhyapan/protocol/openid-connect/certs