## Config server port
server:
   port: 9999

## Spring database schema
spring:
   jpa:
      show-sql: true
      properties:
         hibernate:
            default_schema: adhyapan

---
## Spring Datasource (DatasourceAutoConfiguration & DataSourceProperties)
spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/mocktestdb
      username: postgres
      password: root

---

## Security with oauth2
spring:         
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: http://localhost:8083/auth/realms/adhyapan
               jwk-set-uri: http://localhost:8083/auth/realms/adhyapan/protocol/openid-connect/certs
               
---
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring:
   servlet:
      multipart:
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB
 
---         
## File Storage Properties
file:
   upload-dir: F:/var/questions
  
## Logging Properties
logging:
   level:
      org.springframework: ERROR
      com.tms: DEBUG
   pattern:
      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
      file: "%d %p %c{1.} [%t] %m%n"
   file: app.log 
   
## if no active profile, default is 'default'
    
spring:
  profiles:
    active: default